-- Optional manual schema (MySQL / MariaDB). The bot creates these automatically.
CREATE TABLE IF NOT EXISTS guilds        (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS warnings      (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS levels        (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS economy       (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS tickets       (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS giveaways     (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS polls         (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS reminders     (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS notifications (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
CREATE TABLE IF NOT EXISTS rolemenus     (id VARCHAR(255) PRIMARY KEY, data JSON NOT NULL);
